apiVersion: v1
kind: Pod
metadata:
  name: python-microservice-pod
  namespace: tech.prod
  labels:
    app: python-microservice
spec:
  containers:
  - name: python-microservice-container
    image: ghcr.io/juanesvelez/million-repo:1.0
    resources:
      limits:
        memory: "3Gi"
    ports:
    - containerPort: 80
    env:
    - name: ENVIRONMENT
      value: "production"
    - name: INTERNAL_NETWORK
      value: "internal prod"
  restartPolicy: Always